/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 2
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__newlines_token1 = 1,
  anon_sym_COLON = 2,
  sym_comment_delimeter = 3,
  sym_comment_property = 4,
  sym_comment_string = 5,
  aux_sym_task_token1 = 6,
  anon_sym_BANG = 7,
  anon_sym_COLON2 = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  aux_sym__scope_name_token1 = 12,
  sym_url = 13,
  sym_issue_reference = 14,
  sym_code = 15,
  sym_italic = 16,
  sym_bold = 17,
  sym_autolink = 18,
  sym_single_quote = 19,
  sym_double_quote = 20,
  sym_number = 21,
  sym_punctuation = 22,
  sym_mention = 23,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 24,
  aux_sym_code_block_token1 = 25,
  aux_sym_code_block_token2 = 26,
  aux_sym_code_block_content_token1 = 27,
  aux_sym_code_block_content_token2 = 28,
  sym_documentation = 29,
  sym__documentation_component = 30,
  sym__newlines = 31,
  sym_comment = 32,
  sym__property_comment = 33,
  sym__content_comment = 34,
  sym_task = 35,
  sym_task_scope = 36,
  sym__scope_name = 37,
  sym_string = 38,
  sym__string_component = 39,
  sym_word = 40,
  sym_code_block = 41,
  sym_code_block_content = 42,
  aux_sym_documentation_repeat1 = 43,
  aux_sym_task_scope_repeat1 = 44,
  aux_sym_string_repeat1 = 45,
  aux_sym_code_block_content_repeat1 = 46,
  alias_sym_end_delimeter = 47,
  alias_sym_line = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__newlines_token1] = "_newlines_token1",
  [anon_sym_COLON] = ":",
  [sym_comment_delimeter] = "comment_delimeter",
  [sym_comment_property] = "string",
  [sym_comment_string] = "string",
  [aux_sym_task_token1] = "task_token1",
  [anon_sym_BANG] = "breaking",
  [anon_sym_COLON2] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [aux_sym__scope_name_token1] = "string",
  [sym_url] = "url",
  [sym_issue_reference] = "issue_reference",
  [sym_code] = "code",
  [sym_italic] = "italic",
  [sym_bold] = "bold",
  [sym_autolink] = "autolink",
  [sym_single_quote] = "single_quote",
  [sym_double_quote] = "double_quote",
  [sym_number] = "number",
  [sym_punctuation] = "punctuation",
  [sym_mention] = "mention",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "start_delimeter",
  [aux_sym_code_block_token1] = "string",
  [aux_sym_code_block_token2] = "code_block_token2",
  [aux_sym_code_block_content_token1] = "code_block_content_token1",
  [aux_sym_code_block_content_token2] = "code_block_content_token2",
  [sym_documentation] = "documentation",
  [sym__documentation_component] = "_documentation_component",
  [sym__newlines] = "_newlines",
  [sym_comment] = "comment",
  [sym__property_comment] = "_property_comment",
  [sym__content_comment] = "_content_comment",
  [sym_task] = "task",
  [sym_task_scope] = "task_scope",
  [sym__scope_name] = "_scope_name",
  [sym_string] = "string",
  [sym__string_component] = "_string_component",
  [sym_word] = "word",
  [sym_code_block] = "code_block",
  [sym_code_block_content] = "code_block_content",
  [aux_sym_documentation_repeat1] = "documentation_repeat1",
  [aux_sym_task_scope_repeat1] = "task_scope_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_code_block_content_repeat1] = "code_block_content_repeat1",
  [alias_sym_end_delimeter] = "end_delimeter",
  [alias_sym_line] = "line",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__newlines_token1] = aux_sym__newlines_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_comment_delimeter] = sym_comment_delimeter,
  [sym_comment_property] = sym_string,
  [sym_comment_string] = sym_string,
  [aux_sym_task_token1] = aux_sym_task_token1,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_COLON2] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym__scope_name_token1] = sym_string,
  [sym_url] = sym_url,
  [sym_issue_reference] = sym_issue_reference,
  [sym_code] = sym_code,
  [sym_italic] = sym_italic,
  [sym_bold] = sym_bold,
  [sym_autolink] = sym_autolink,
  [sym_single_quote] = sym_single_quote,
  [sym_double_quote] = sym_double_quote,
  [sym_number] = sym_number,
  [sym_punctuation] = sym_punctuation,
  [sym_mention] = sym_mention,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [aux_sym_code_block_token1] = sym_string,
  [aux_sym_code_block_token2] = aux_sym_code_block_token2,
  [aux_sym_code_block_content_token1] = aux_sym_code_block_content_token1,
  [aux_sym_code_block_content_token2] = aux_sym_code_block_content_token2,
  [sym_documentation] = sym_documentation,
  [sym__documentation_component] = sym__documentation_component,
  [sym__newlines] = sym__newlines,
  [sym_comment] = sym_comment,
  [sym__property_comment] = sym__property_comment,
  [sym__content_comment] = sym__content_comment,
  [sym_task] = sym_task,
  [sym_task_scope] = sym_task_scope,
  [sym__scope_name] = sym__scope_name,
  [sym_string] = sym_string,
  [sym__string_component] = sym__string_component,
  [sym_word] = sym_word,
  [sym_code_block] = sym_code_block,
  [sym_code_block_content] = sym_code_block_content,
  [aux_sym_documentation_repeat1] = aux_sym_documentation_repeat1,
  [aux_sym_task_scope_repeat1] = aux_sym_task_scope_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_code_block_content_repeat1] = aux_sym_code_block_content_repeat1,
  [alias_sym_end_delimeter] = alias_sym_end_delimeter,
  [alias_sym_line] = alias_sym_line,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__newlines_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_delimeter] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_property] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_task_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__scope_name_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_issue_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_autolink] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_mention] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_block_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_block_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_content_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_documentation] = {
    .visible = true,
    .named = true,
  },
  [sym__documentation_component] = {
    .visible = false,
    .named = true,
  },
  [sym__newlines] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__property_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__content_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_task_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__scope_name] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_component] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_documentation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_task_scope_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_end_delimeter] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_line] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_description = 2,
  field_language = 3,
  field_property = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_description] = "description",
  [field_language] = "language",
  [field_property] = "property",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 0, .inherited = true},
    {field_property, 0, .inherited = true},
  [2] =
    {field_content, 0, .inherited = true},
  [3] =
    {field_content, 1},
  [4] =
    {field_description, 2},
    {field_type, 0},
  [6] =
    {field_content, 3},
    {field_property, 1},
  [8] =
    {field_description, 3},
    {field_type, 0},
  [10] =
    {field_content, 2},
  [11] =
    {field_description, 4},
    {field_type, 0},
  [13] =
    {field_content, 3},
    {field_language, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = alias_sym_line,
  },
  [5] = {
    [0] = sym_string,
  },
  [7] = {
    [0] = sym_string,
  },
  [8] = {
    [3] = alias_sym_end_delimeter,
  },
  [9] = {
    [0] = sym_string,
  },
  [10] = {
    [4] = alias_sym_end_delimeter,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_string, 2,
    sym_string,
    alias_sym_line,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static const TSCharacterRange sym_punctuation_character_set_1[] = {
  {'!', '#'}, {'%', '*'}, {',', '/'}, {':', ';'}, {'?', '@'}, {'[', ']'}, {'_', '_'}, {'{', '{'},
  {'}', '}'}, {0xa1, 0xa1}, {0xa7, 0xa7}, {0xab, 0xab}, {0xb6, 0xb7}, {0xbb, 0xbb}, {0xbf, 0xbf}, {0x37e, 0x37e},
  {0x387, 0x387}, {0x55a, 0x55f}, {0x589, 0x58a}, {0x5be, 0x5be}, {0x5c0, 0x5c0}, {0x5c3, 0x5c3}, {0x5c6, 0x5c6}, {0x5f3, 0x5f4},
  {0x609, 0x60a}, {0x60c, 0x60d}, {0x61b, 0x61b}, {0x61d, 0x61f}, {0x66a, 0x66d}, {0x6d4, 0x6d4}, {0x700, 0x70d}, {0x7f7, 0x7f9},
  {0x830, 0x83e}, {0x85e, 0x85e}, {0x964, 0x965}, {0x970, 0x970}, {0x9fd, 0x9fd}, {0xa76, 0xa76}, {0xaf0, 0xaf0}, {0xc77, 0xc77},
  {0xc84, 0xc84}, {0xdf4, 0xdf4}, {0xe4f, 0xe4f}, {0xe5a, 0xe5b}, {0xf04, 0xf12}, {0xf14, 0xf14}, {0xf3a, 0xf3d}, {0xf85, 0xf85},
  {0xfd0, 0xfd4}, {0xfd9, 0xfda}, {0x104a, 0x104f}, {0x10fb, 0x10fb}, {0x1360, 0x1368}, {0x1400, 0x1400}, {0x166e, 0x166e}, {0x169b, 0x169c},
  {0x16eb, 0x16ed}, {0x1735, 0x1736}, {0x17d4, 0x17d6}, {0x17d8, 0x17da}, {0x1800, 0x180a}, {0x1944, 0x1945}, {0x1a1e, 0x1a1f}, {0x1aa0, 0x1aa6},
  {0x1aa8, 0x1aad}, {0x1b4e, 0x1b4f}, {0x1b5a, 0x1b60}, {0x1b7d, 0x1b7f}, {0x1bfc, 0x1bff}, {0x1c3b, 0x1c3f}, {0x1c7e, 0x1c7f}, {0x1cc0, 0x1cc7},
  {0x1cd3, 0x1cd3}, {0x2010, 0x2027}, {0x2030, 0x2043}, {0x2045, 0x2051}, {0x2053, 0x205e}, {0x207d, 0x207e}, {0x208d, 0x208e}, {0x2308, 0x230b},
  {0x2329, 0x232a}, {0x2768, 0x2775}, {0x27c5, 0x27c6}, {0x27e6, 0x27ef}, {0x2983, 0x2998}, {0x29d8, 0x29db}, {0x29fc, 0x29fd}, {0x2cf9, 0x2cfc},
  {0x2cfe, 0x2cff}, {0x2d70, 0x2d70}, {0x2e00, 0x2e2e}, {0x2e30, 0x2e4f}, {0x2e52, 0x2e5d}, {0x3001, 0x3003}, {0x3008, 0x3011}, {0x3014, 0x301f},
  {0x3030, 0x3030}, {0x303d, 0x303d}, {0x30a0, 0x30a0}, {0x30fb, 0x30fb}, {0xa4fe, 0xa4ff}, {0xa60d, 0xa60f}, {0xa673, 0xa673}, {0xa67e, 0xa67e},
  {0xa6f2, 0xa6f7}, {0xa874, 0xa877}, {0xa8ce, 0xa8cf}, {0xa8f8, 0xa8fa}, {0xa8fc, 0xa8fc}, {0xa92e, 0xa92f}, {0xa95f, 0xa95f}, {0xa9c1, 0xa9cd},
  {0xa9de, 0xa9df}, {0xaa5c, 0xaa5f}, {0xaade, 0xaadf}, {0xaaf0, 0xaaf1}, {0xabeb, 0xabeb}, {0xfd3e, 0xfd3f}, {0xfe10, 0xfe19}, {0xfe30, 0xfe52},
  {0xfe54, 0xfe61}, {0xfe63, 0xfe63}, {0xfe68, 0xfe68}, {0xfe6a, 0xfe6b}, {0xff01, 0xff03}, {0xff05, 0xff0a}, {0xff0c, 0xff0f}, {0xff1a, 0xff1b},
  {0xff1f, 0xff20}, {0xff3b, 0xff3d}, {0xff3f, 0xff3f}, {0xff5b, 0xff5b}, {0xff5d, 0xff5d}, {0xff5f, 0xff65}, {0x10100, 0x10102}, {0x1039f, 0x1039f},
  {0x103d0, 0x103d0}, {0x1056f, 0x1056f}, {0x10857, 0x10857}, {0x1091f, 0x1091f}, {0x1093f, 0x1093f}, {0x10a50, 0x10a58}, {0x10a7f, 0x10a7f}, {0x10af0, 0x10af6},
  {0x10b39, 0x10b3f}, {0x10b99, 0x10b9c}, {0x10d6e, 0x10d6e}, {0x10ead, 0x10ead}, {0x10f55, 0x10f59}, {0x10f86, 0x10f89}, {0x11047, 0x1104d}, {0x110bb, 0x110bc},
  {0x110be, 0x110c1}, {0x11140, 0x11143}, {0x11174, 0x11175}, {0x111c5, 0x111c8}, {0x111cd, 0x111cd}, {0x111db, 0x111db}, {0x111dd, 0x111df}, {0x11238, 0x1123d},
  {0x112a9, 0x112a9}, {0x113d4, 0x113d5}, {0x113d7, 0x113d8}, {0x1144b, 0x1144f}, {0x1145a, 0x1145b}, {0x1145d, 0x1145d}, {0x114c6, 0x114c6}, {0x115c1, 0x115d7},
  {0x11641, 0x11643}, {0x11660, 0x1166c}, {0x116b9, 0x116b9}, {0x1173c, 0x1173e}, {0x1183b, 0x1183b}, {0x11944, 0x11946}, {0x119e2, 0x119e2}, {0x11a3f, 0x11a46},
  {0x11a9a, 0x11a9c}, {0x11a9e, 0x11aa2}, {0x11b00, 0x11b09}, {0x11be1, 0x11be1}, {0x11c41, 0x11c45}, {0x11c70, 0x11c71}, {0x11ef7, 0x11ef8}, {0x11f43, 0x11f4f},
  {0x11fff, 0x11fff}, {0x12470, 0x12474}, {0x12ff1, 0x12ff2}, {0x16a6e, 0x16a6f}, {0x16af5, 0x16af5}, {0x16b37, 0x16b3b}, {0x16b44, 0x16b44}, {0x16d6d, 0x16d6f},
  {0x16e97, 0x16e9a}, {0x16fe2, 0x16fe2}, {0x1bc9f, 0x1bc9f}, {0x1da87, 0x1da8b}, {0x1e5ff, 0x1e5ff}, {0x1e95e, 0x1e95f},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '\n', 52,
        '\r', 52,
        '!', 67,
        '"', 93,
        '#', 54,
        '\'', 94,
        '(', 69,
        ')', 71,
        '*', 95,
        ',', 70,
        '-', 96,
        '.', 98,
        ':', 68,
        '<', 44,
        '@', 99,
        '_', 66,
        '`', 25,
        'h', 63,
        'w', 65,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(92);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 103,
        '"', 93,
        '#', 97,
        '\'', 94,
        '*', 95,
        '-', 96,
        '.', 98,
        '<', 44,
        '@', 99,
        '_', 66,
        '`', 29,
        'h', 63,
        'w', 65,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(92);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(103);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(89);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(90);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == ')') ADVANCE(71);
      if (lookahead == ',') ADVANCE(70);
      if (lookahead == '@') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(75);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(87);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(81);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(84);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(85);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == '*') ADVANCE(83);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == ',') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 19:
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == '1') ADVANCE(15);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == '1') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == '2') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == '2') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == '>') ADVANCE(86);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(80);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 29:
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 30:
      if (lookahead == '\\') ADVANCE(106);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(108);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 31:
      if (lookahead == '`') ADVANCE(101);
      END_STATE();
    case 32:
      if (lookahead == '`') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 33:
      if (lookahead == '`') ADVANCE(31);
      if (lookahead == '{') ADVANCE(21);
      END_STATE();
    case 34:
      if (lookahead == '}') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(36);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 40:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 41:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(76);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ':') ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(56);
      END_STATE();
    case 44:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(24);
      END_STATE();
    case 45:
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(108);
      END_STATE();
    case 46:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '\n', 52,
        '\r', 52,
        '"', 93,
        '#', 54,
        '\'', 94,
        '(', 69,
        ')', 71,
        '*', 95,
        ',', 70,
        '-', 96,
        '.', 98,
        ':', 53,
        '<', 44,
        '@', 99,
        '_', 66,
        '`', 25,
        'h', 63,
        'w', 65,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(92);
      END_STATE();
    case 47:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '!', 67,
        '"', 93,
        '#', 54,
        '\'', 94,
        '(', 69,
        '*', 95,
        '-', 96,
        '.', 98,
        ':', 68,
        '<', 44,
        '@', 99,
        '_', 66,
        '`', 26,
        'h', 63,
        'w', 65,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(48);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(92);
      END_STATE();
    case 48:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '"', 93,
        '#', 54,
        '\'', 94,
        '(', 69,
        '*', 95,
        '-', 96,
        '.', 98,
        '<', 44,
        '@', 99,
        '_', 66,
        '`', 26,
        'h', 63,
        'w', 65,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(48);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(92);
      END_STATE();
    case 49:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '"', 93,
        '#', 54,
        '\'', 94,
        '*', 95,
        '-', 96,
        '.', 98,
        ':', 53,
        '<', 44,
        '@', 99,
        '_', 66,
        '`', 26,
        'h', 63,
        'w', 65,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(49);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(92);
      END_STATE();
    case 50:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '"', 93,
        '#', 54,
        '\'', 94,
        '*', 95,
        '-', 96,
        '.', 98,
        '<', 44,
        '@', 99,
        '_', 66,
        '`', 26,
        'h', 63,
        'w', 65,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(50);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(92);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym__newlines_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_comment_delimeter);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_comment_property);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ':') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_comment_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '/') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == ':') ADVANCE(19);
      if (lookahead == 's') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == ':') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == 'p') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == 't') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == 't') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == 'w') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == 'w') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '/') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_COLON2);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym__scope_name_token1);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '@' || 'Z' < lookahead)) ADVANCE(75);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym__scope_name_token1);
      if (lookahead == '/') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '@' || 'Z' < lookahead)) ADVANCE(75);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym__scope_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '@' || 'Z' < lookahead)) ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym__scope_name_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '@') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_issue_reference);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_code);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_code);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_code);
      if (lookahead == '`') ADVANCE(101);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_italic);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_italic);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_italic);
      if (lookahead == '*') ADVANCE(81);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_bold);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_bold);
      if (lookahead == '*') ADVANCE(84);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_autolink);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_single_quote);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_single_quote);
      if (lookahead == '\'') ADVANCE(87);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_double_quote);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_double_quote);
      if (lookahead == '"') ADVANCE(89);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '"') ADVANCE(89);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '\'') ADVANCE(87);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '*') ADVANCE(82);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_punctuation);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_punctuation);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_punctuation);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_mention);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_code_block_token2);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_code_block_content_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_code_block_content_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_code_block_content_token2);
      if (lookahead == '\\') ADVANCE(106);
      if (lookahead == '`') ADVANCE(79);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(108);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_code_block_content_token2);
      if (lookahead == '\\') ADVANCE(106);
      if (lookahead == '`') ADVANCE(78);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(108);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_code_block_content_token2);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(108);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 50},
  [2] = {.lex_state = 50},
  [3] = {.lex_state = 50},
  [4] = {.lex_state = 47},
  [5] = {.lex_state = 50},
  [6] = {.lex_state = 50},
  [7] = {.lex_state = 49},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 50},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 50},
  [12] = {.lex_state = 50},
  [13] = {.lex_state = 50},
  [14] = {.lex_state = 50},
  [15] = {.lex_state = 50},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 50},
  [18] = {.lex_state = 50},
  [19] = {.lex_state = 50},
  [20] = {.lex_state = 50},
  [21] = {.lex_state = 32},
  [22] = {.lex_state = 32},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 32},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 32},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 47},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 47},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 47},
  [35] = {.lex_state = 47},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 35},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 47},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 36},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__newlines_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_comment_delimeter] = ACTIONS(1),
    [aux_sym_task_token1] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_COLON2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_url] = ACTIONS(1),
    [sym_issue_reference] = ACTIONS(1),
    [sym_code] = ACTIONS(1),
    [sym_italic] = ACTIONS(1),
    [sym_bold] = ACTIONS(1),
    [sym_autolink] = ACTIONS(1),
    [sym_single_quote] = ACTIONS(1),
    [sym_double_quote] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_mention] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [aux_sym_code_block_token2] = ACTIONS(1),
    [aux_sym_code_block_content_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_documentation] = STATE(41),
    [sym__documentation_component] = STATE(2),
    [sym__newlines] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__property_comment] = STATE(12),
    [sym__content_comment] = STATE(18),
    [sym_task] = STATE(2),
    [sym_string] = STATE(9),
    [sym__string_component] = STATE(6),
    [sym_word] = STATE(6),
    [sym_code_block] = STATE(2),
    [aux_sym_documentation_repeat1] = STATE(2),
    [aux_sym_string_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__newlines_token1] = ACTIONS(5),
    [sym_comment_delimeter] = ACTIONS(7),
    [aux_sym_task_token1] = ACTIONS(9),
    [sym_url] = ACTIONS(11),
    [sym_issue_reference] = ACTIONS(11),
    [sym_code] = ACTIONS(13),
    [sym_italic] = ACTIONS(13),
    [sym_bold] = ACTIONS(11),
    [sym_autolink] = ACTIONS(11),
    [sym_single_quote] = ACTIONS(11),
    [sym_double_quote] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [sym_punctuation] = ACTIONS(13),
    [sym_mention] = ACTIONS(11),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__documentation_component] = STATE(3),
    [sym__newlines] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__property_comment] = STATE(12),
    [sym__content_comment] = STATE(18),
    [sym_task] = STATE(3),
    [sym_string] = STATE(9),
    [sym__string_component] = STATE(6),
    [sym_word] = STATE(6),
    [sym_code_block] = STATE(3),
    [aux_sym_documentation_repeat1] = STATE(3),
    [aux_sym_string_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(17),
    [aux_sym__newlines_token1] = ACTIONS(19),
    [sym_comment_delimeter] = ACTIONS(7),
    [aux_sym_task_token1] = ACTIONS(9),
    [sym_url] = ACTIONS(11),
    [sym_issue_reference] = ACTIONS(11),
    [sym_code] = ACTIONS(13),
    [sym_italic] = ACTIONS(13),
    [sym_bold] = ACTIONS(11),
    [sym_autolink] = ACTIONS(11),
    [sym_single_quote] = ACTIONS(11),
    [sym_double_quote] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [sym_punctuation] = ACTIONS(13),
    [sym_mention] = ACTIONS(11),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__documentation_component] = STATE(3),
    [sym__newlines] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__property_comment] = STATE(12),
    [sym__content_comment] = STATE(18),
    [sym_task] = STATE(3),
    [sym_string] = STATE(9),
    [sym__string_component] = STATE(6),
    [sym_word] = STATE(6),
    [sym_code_block] = STATE(3),
    [aux_sym_documentation_repeat1] = STATE(3),
    [aux_sym_string_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(21),
    [aux_sym__newlines_token1] = ACTIONS(23),
    [sym_comment_delimeter] = ACTIONS(26),
    [aux_sym_task_token1] = ACTIONS(29),
    [sym_url] = ACTIONS(32),
    [sym_issue_reference] = ACTIONS(32),
    [sym_code] = ACTIONS(35),
    [sym_italic] = ACTIONS(35),
    [sym_bold] = ACTIONS(32),
    [sym_autolink] = ACTIONS(32),
    [sym_single_quote] = ACTIONS(32),
    [sym_double_quote] = ACTIONS(32),
    [sym_number] = ACTIONS(35),
    [sym_punctuation] = ACTIONS(35),
    [sym_mention] = ACTIONS(32),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(45), 1,
      anon_sym_BANG,
    ACTIONS(47), 1,
      anon_sym_COLON2,
    ACTIONS(49), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_task_scope,
    ACTIONS(43), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(41), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [33] = 6,
    ACTIONS(53), 1,
      sym_comment_delimeter,
    ACTIONS(55), 1,
      aux_sym_task_token1,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(5), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(61), 4,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(58), 7,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [65] = 6,
    ACTIONS(66), 1,
      sym_comment_delimeter,
    ACTIONS(68), 1,
      aux_sym_task_token1,
    ACTIONS(64), 3,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(5), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(72), 4,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(70), 7,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [97] = 3,
    ACTIONS(76), 1,
      anon_sym_COLON,
    ACTIONS(78), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(74), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [121] = 5,
    ACTIONS(68), 1,
      aux_sym_task_token1,
    STATE(15), 1,
      sym_string,
    ACTIONS(13), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(6), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(11), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [148] = 2,
    ACTIONS(82), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(80), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [169] = 5,
    ACTIONS(68), 1,
      aux_sym_task_token1,
    STATE(13), 1,
      sym_string,
    ACTIONS(13), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(6), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(11), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [196] = 2,
    ACTIONS(43), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(41), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [217] = 2,
    ACTIONS(86), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(84), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [238] = 2,
    ACTIONS(90), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(88), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [259] = 2,
    ACTIONS(94), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(92), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [280] = 2,
    ACTIONS(98), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(96), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [301] = 5,
    ACTIONS(68), 1,
      aux_sym_task_token1,
    STATE(19), 1,
      sym_string,
    ACTIONS(13), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(6), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(11), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [328] = 2,
    ACTIONS(102), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(100), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [349] = 2,
    ACTIONS(106), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(104), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [370] = 2,
    ACTIONS(110), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(108), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [391] = 2,
    ACTIONS(114), 6,
      sym_comment_delimeter,
      aux_sym_task_token1,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(112), 10,
      ts_builtin_sym_end,
      aux_sym__newlines_token1,
      sym_url,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [412] = 4,
    ACTIONS(116), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(118), 1,
      aux_sym_code_block_content_token1,
    ACTIONS(121), 1,
      aux_sym_code_block_content_token2,
    STATE(21), 1,
      aux_sym_code_block_content_repeat1,
  [425] = 4,
    ACTIONS(124), 1,
      aux_sym_code_block_content_token1,
    ACTIONS(126), 1,
      aux_sym_code_block_content_token2,
    STATE(24), 1,
      aux_sym_code_block_content_repeat1,
    STATE(40), 1,
      sym_code_block_content,
  [438] = 3,
    ACTIONS(128), 1,
      aux_sym__scope_name_token1,
    STATE(27), 1,
      sym__scope_name,
    ACTIONS(130), 2,
      sym_issue_reference,
      sym_mention,
  [449] = 4,
    ACTIONS(132), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(134), 1,
      aux_sym_code_block_content_token1,
    ACTIONS(136), 1,
      aux_sym_code_block_content_token2,
    STATE(21), 1,
      aux_sym_code_block_content_repeat1,
  [462] = 3,
    ACTIONS(138), 1,
      aux_sym__scope_name_token1,
    STATE(33), 1,
      sym__scope_name,
    ACTIONS(140), 2,
      sym_issue_reference,
      sym_mention,
  [473] = 4,
    ACTIONS(124), 1,
      aux_sym_code_block_content_token1,
    ACTIONS(126), 1,
      aux_sym_code_block_content_token2,
    STATE(24), 1,
      aux_sym_code_block_content_repeat1,
    STATE(36), 1,
      sym_code_block_content,
  [486] = 3,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_task_scope_repeat1,
  [496] = 3,
    ACTIONS(142), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_task_scope_repeat1,
  [506] = 3,
    ACTIONS(148), 1,
      anon_sym_COMMA,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_task_scope_repeat1,
  [516] = 2,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_COLON2,
  [523] = 2,
    ACTIONS(157), 1,
      aux_sym_code_block_token1,
    ACTIONS(159), 1,
      aux_sym_code_block_token2,
  [530] = 1,
    ACTIONS(161), 2,
      anon_sym_BANG,
      anon_sym_COLON2,
  [535] = 1,
    ACTIONS(151), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [540] = 1,
    ACTIONS(163), 2,
      anon_sym_BANG,
      anon_sym_COLON2,
  [545] = 1,
    ACTIONS(165), 1,
      anon_sym_COLON2,
  [549] = 1,
    ACTIONS(167), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [553] = 1,
    ACTIONS(169), 1,
      sym_comment_property,
  [557] = 1,
    ACTIONS(171), 1,
      aux_sym_code_block_token2,
  [561] = 1,
    ACTIONS(155), 1,
      anon_sym_COLON2,
  [565] = 1,
    ACTIONS(173), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [569] = 1,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
  [573] = 1,
    ACTIONS(177), 1,
      sym_comment_string,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 33,
  [SMALL_STATE(6)] = 65,
  [SMALL_STATE(7)] = 97,
  [SMALL_STATE(8)] = 121,
  [SMALL_STATE(9)] = 148,
  [SMALL_STATE(10)] = 169,
  [SMALL_STATE(11)] = 196,
  [SMALL_STATE(12)] = 217,
  [SMALL_STATE(13)] = 238,
  [SMALL_STATE(14)] = 259,
  [SMALL_STATE(15)] = 280,
  [SMALL_STATE(16)] = 301,
  [SMALL_STATE(17)] = 328,
  [SMALL_STATE(18)] = 349,
  [SMALL_STATE(19)] = 370,
  [SMALL_STATE(20)] = 391,
  [SMALL_STATE(21)] = 412,
  [SMALL_STATE(22)] = 425,
  [SMALL_STATE(23)] = 438,
  [SMALL_STATE(24)] = 449,
  [SMALL_STATE(25)] = 462,
  [SMALL_STATE(26)] = 473,
  [SMALL_STATE(27)] = 486,
  [SMALL_STATE(28)] = 496,
  [SMALL_STATE(29)] = 506,
  [SMALL_STATE(30)] = 516,
  [SMALL_STATE(31)] = 523,
  [SMALL_STATE(32)] = 530,
  [SMALL_STATE(33)] = 535,
  [SMALL_STATE(34)] = 540,
  [SMALL_STATE(35)] = 545,
  [SMALL_STATE(36)] = 549,
  [SMALL_STATE(37)] = 553,
  [SMALL_STATE(38)] = 557,
  [SMALL_STATE(39)] = 561,
  [SMALL_STATE(40)] = 565,
  [SMALL_STATE(41)] = 569,
  [SMALL_STATE(42)] = 573,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_documentation, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_documentation, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__content_comment, 2, 0, 4),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__content_comment, 2, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__documentation_component, 1, 0, 3),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__documentation_component, 1, 0, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 3, 0, 5),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 3, 0, 5),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__property_comment, 4, 0, 6),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__property_comment, 4, 0, 6),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 4, 0, 7),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 4, 0, 7),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4, 0, 8),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4, 0, 8),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 2),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 5, 0, 9),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 5, 0, 9),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 10),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 5, 0, 10),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_block_content_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_block_content_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [121] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_block_content_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block_content, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_task_scope_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_scope, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_scope, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [175] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_doctext(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "doctext",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
