/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 2
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_documentation_token1 = 1,
  anon_sym_COLON = 2,
  sym_comment_delimeter = 3,
  sym_comment_property = 4,
  sym_comment_string = 5,
  aux_sym_task_token1 = 6,
  anon_sym_BANG = 7,
  anon_sym_COLON2 = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  aux_sym__scope_name_token1 = 12,
  aux_sym_footer_token1 = 13,
  anon_sym_BREAKINGCHANGE = 14,
  aux_sym_footer_type_token1 = 15,
  sym_url = 16,
  sym_issue_reference = 17,
  sym_code = 18,
  sym_italic = 19,
  sym_bold = 20,
  sym_autolink = 21,
  sym_single_quote = 22,
  sym_double_quote = 23,
  sym_number = 24,
  sym_punctuation = 25,
  sym_mention = 26,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 27,
  aux_sym_code_block_token1 = 28,
  aux_sym_code_block_token2 = 29,
  aux_sym_code_block_content_token1 = 30,
  aux_sym_code_block_content_token2 = 31,
  sym_newlinw_or_eof = 32,
  sym_documentation = 33,
  sym__documentation_component = 34,
  sym_comment = 35,
  sym__property_comment = 36,
  sym__content_comment = 37,
  sym_task = 38,
  sym_task_scope = 39,
  sym__scope_name = 40,
  sym_footer = 41,
  sym_footer_type = 42,
  sym_string = 43,
  sym__string_component = 44,
  sym_word = 45,
  sym_code_block = 46,
  sym_code_block_content = 47,
  aux_sym_documentation_repeat1 = 48,
  aux_sym_task_scope_repeat1 = 49,
  aux_sym_string_repeat1 = 50,
  aux_sym_code_block_content_repeat1 = 51,
  alias_sym_end_delimeter = 52,
  alias_sym_line = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_documentation_token1] = "documentation_token1",
  [anon_sym_COLON] = ":",
  [sym_comment_delimeter] = "comment_delimeter",
  [sym_comment_property] = "string",
  [sym_comment_string] = "string",
  [aux_sym_task_token1] = "task_token1",
  [anon_sym_BANG] = "breaking",
  [anon_sym_COLON2] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [aux_sym__scope_name_token1] = "string",
  [aux_sym_footer_token1] = "footer_token1",
  [anon_sym_BREAKINGCHANGE] = "BREAKING CHANGE",
  [aux_sym_footer_type_token1] = "footer_type_token1",
  [sym_url] = "url",
  [sym_issue_reference] = "issue_reference",
  [sym_code] = "code",
  [sym_italic] = "italic",
  [sym_bold] = "bold",
  [sym_autolink] = "autolink",
  [sym_single_quote] = "single_quote",
  [sym_double_quote] = "double_quote",
  [sym_number] = "number",
  [sym_punctuation] = "punctuation",
  [sym_mention] = "mention",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "start_delimeter",
  [aux_sym_code_block_token1] = "string",
  [aux_sym_code_block_token2] = "code_block_token2",
  [aux_sym_code_block_content_token1] = "code_block_content_token1",
  [aux_sym_code_block_content_token2] = "code_block_content_token2",
  [sym_newlinw_or_eof] = "newlinw_or_eof",
  [sym_documentation] = "documentation",
  [sym__documentation_component] = "_documentation_component",
  [sym_comment] = "comment",
  [sym__property_comment] = "_property_comment",
  [sym__content_comment] = "_content_comment",
  [sym_task] = "task",
  [sym_task_scope] = "task_scope",
  [sym__scope_name] = "_scope_name",
  [sym_footer] = "footer",
  [sym_footer_type] = "string",
  [sym_string] = "string",
  [sym__string_component] = "_string_component",
  [sym_word] = "word",
  [sym_code_block] = "code_block",
  [sym_code_block_content] = "code_block_content",
  [aux_sym_documentation_repeat1] = "documentation_repeat1",
  [aux_sym_task_scope_repeat1] = "task_scope_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_code_block_content_repeat1] = "code_block_content_repeat1",
  [alias_sym_end_delimeter] = "end_delimeter",
  [alias_sym_line] = "line",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_documentation_token1] = aux_sym_documentation_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_comment_delimeter] = sym_comment_delimeter,
  [sym_comment_property] = sym_string,
  [sym_comment_string] = sym_string,
  [aux_sym_task_token1] = aux_sym_task_token1,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_COLON2] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym__scope_name_token1] = sym_string,
  [aux_sym_footer_token1] = aux_sym_footer_token1,
  [anon_sym_BREAKINGCHANGE] = anon_sym_BREAKINGCHANGE,
  [aux_sym_footer_type_token1] = aux_sym_footer_type_token1,
  [sym_url] = sym_url,
  [sym_issue_reference] = sym_issue_reference,
  [sym_code] = sym_code,
  [sym_italic] = sym_italic,
  [sym_bold] = sym_bold,
  [sym_autolink] = sym_autolink,
  [sym_single_quote] = sym_single_quote,
  [sym_double_quote] = sym_double_quote,
  [sym_number] = sym_number,
  [sym_punctuation] = sym_punctuation,
  [sym_mention] = sym_mention,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [aux_sym_code_block_token1] = sym_string,
  [aux_sym_code_block_token2] = aux_sym_code_block_token2,
  [aux_sym_code_block_content_token1] = aux_sym_code_block_content_token1,
  [aux_sym_code_block_content_token2] = aux_sym_code_block_content_token2,
  [sym_newlinw_or_eof] = sym_newlinw_or_eof,
  [sym_documentation] = sym_documentation,
  [sym__documentation_component] = sym__documentation_component,
  [sym_comment] = sym_comment,
  [sym__property_comment] = sym__property_comment,
  [sym__content_comment] = sym__content_comment,
  [sym_task] = sym_task,
  [sym_task_scope] = sym_task_scope,
  [sym__scope_name] = sym__scope_name,
  [sym_footer] = sym_footer,
  [sym_footer_type] = sym_string,
  [sym_string] = sym_string,
  [sym__string_component] = sym__string_component,
  [sym_word] = sym_word,
  [sym_code_block] = sym_code_block,
  [sym_code_block_content] = sym_code_block_content,
  [aux_sym_documentation_repeat1] = aux_sym_documentation_repeat1,
  [aux_sym_task_scope_repeat1] = aux_sym_task_scope_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_code_block_content_repeat1] = aux_sym_code_block_content_repeat1,
  [alias_sym_end_delimeter] = alias_sym_end_delimeter,
  [alias_sym_line] = alias_sym_line,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_documentation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_delimeter] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_property] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_task_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__scope_name_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_footer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BREAKINGCHANGE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_footer_type_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_issue_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_autolink] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_mention] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_block_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_block_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_content_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_newlinw_or_eof] = {
    .visible = true,
    .named = true,
  },
  [sym_documentation] = {
    .visible = true,
    .named = true,
  },
  [sym__documentation_component] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__property_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__content_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_task_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__scope_name] = {
    .visible = false,
    .named = true,
  },
  [sym_footer] = {
    .visible = true,
    .named = true,
  },
  [sym_footer_type] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_component] = {
    .visible = false,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_documentation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_task_scope_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_end_delimeter] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_line] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_description = 2,
  field_language = 3,
  field_property = 4,
  field_type = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_description] = "description",
  [field_language] = "language",
  [field_property] = "property",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 4, .length = 2},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 8, .length = 2},
  [9] = {.index = 10, .length = 1},
  [10] = {.index = 11, .length = 2},
  [11] = {.index = 13, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 0, .inherited = true},
    {field_property, 0, .inherited = true},
  [2] =
    {field_content, 0, .inherited = true},
  [3] =
    {field_content, 1},
  [4] =
    {field_description, 2},
    {field_type, 0},
  [6] =
    {field_content, 3},
    {field_property, 1},
  [8] =
    {field_description, 3},
    {field_type, 0},
  [10] =
    {field_content, 2},
  [11] =
    {field_description, 4},
    {field_type, 0},
  [13] =
    {field_content, 3},
    {field_language, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = alias_sym_line,
  },
  [5] = {
    [0] = sym_string,
  },
  [8] = {
    [0] = sym_string,
  },
  [9] = {
    [3] = alias_sym_end_delimeter,
  },
  [10] = {
    [0] = sym_string,
  },
  [11] = {
    [4] = alias_sym_end_delimeter,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_string, 2,
    sym_string,
    alias_sym_line,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
};

static const TSCharacterRange sym_punctuation_character_set_1[] = {
  {'!', '#'}, {'%', '*'}, {',', '/'}, {':', ';'}, {'?', '@'}, {'[', ']'}, {'_', '_'}, {'{', '{'},
  {'}', '}'}, {0xa1, 0xa1}, {0xa7, 0xa7}, {0xab, 0xab}, {0xb6, 0xb7}, {0xbb, 0xbb}, {0xbf, 0xbf}, {0x37e, 0x37e},
  {0x387, 0x387}, {0x55a, 0x55f}, {0x589, 0x58a}, {0x5be, 0x5be}, {0x5c0, 0x5c0}, {0x5c3, 0x5c3}, {0x5c6, 0x5c6}, {0x5f3, 0x5f4},
  {0x609, 0x60a}, {0x60c, 0x60d}, {0x61b, 0x61b}, {0x61d, 0x61f}, {0x66a, 0x66d}, {0x6d4, 0x6d4}, {0x700, 0x70d}, {0x7f7, 0x7f9},
  {0x830, 0x83e}, {0x85e, 0x85e}, {0x964, 0x965}, {0x970, 0x970}, {0x9fd, 0x9fd}, {0xa76, 0xa76}, {0xaf0, 0xaf0}, {0xc77, 0xc77},
  {0xc84, 0xc84}, {0xdf4, 0xdf4}, {0xe4f, 0xe4f}, {0xe5a, 0xe5b}, {0xf04, 0xf12}, {0xf14, 0xf14}, {0xf3a, 0xf3d}, {0xf85, 0xf85},
  {0xfd0, 0xfd4}, {0xfd9, 0xfda}, {0x104a, 0x104f}, {0x10fb, 0x10fb}, {0x1360, 0x1368}, {0x1400, 0x1400}, {0x166e, 0x166e}, {0x169b, 0x169c},
  {0x16eb, 0x16ed}, {0x1735, 0x1736}, {0x17d4, 0x17d6}, {0x17d8, 0x17da}, {0x1800, 0x180a}, {0x1944, 0x1945}, {0x1a1e, 0x1a1f}, {0x1aa0, 0x1aa6},
  {0x1aa8, 0x1aad}, {0x1b4e, 0x1b4f}, {0x1b5a, 0x1b60}, {0x1b7d, 0x1b7f}, {0x1bfc, 0x1bff}, {0x1c3b, 0x1c3f}, {0x1c7e, 0x1c7f}, {0x1cc0, 0x1cc7},
  {0x1cd3, 0x1cd3}, {0x2010, 0x2027}, {0x2030, 0x2043}, {0x2045, 0x2051}, {0x2053, 0x205e}, {0x207d, 0x207e}, {0x208d, 0x208e}, {0x2308, 0x230b},
  {0x2329, 0x232a}, {0x2768, 0x2775}, {0x27c5, 0x27c6}, {0x27e6, 0x27ef}, {0x2983, 0x2998}, {0x29d8, 0x29db}, {0x29fc, 0x29fd}, {0x2cf9, 0x2cfc},
  {0x2cfe, 0x2cff}, {0x2d70, 0x2d70}, {0x2e00, 0x2e2e}, {0x2e30, 0x2e4f}, {0x2e52, 0x2e5d}, {0x3001, 0x3003}, {0x3008, 0x3011}, {0x3014, 0x301f},
  {0x3030, 0x3030}, {0x303d, 0x303d}, {0x30a0, 0x30a0}, {0x30fb, 0x30fb}, {0xa4fe, 0xa4ff}, {0xa60d, 0xa60f}, {0xa673, 0xa673}, {0xa67e, 0xa67e},
  {0xa6f2, 0xa6f7}, {0xa874, 0xa877}, {0xa8ce, 0xa8cf}, {0xa8f8, 0xa8fa}, {0xa8fc, 0xa8fc}, {0xa92e, 0xa92f}, {0xa95f, 0xa95f}, {0xa9c1, 0xa9cd},
  {0xa9de, 0xa9df}, {0xaa5c, 0xaa5f}, {0xaade, 0xaadf}, {0xaaf0, 0xaaf1}, {0xabeb, 0xabeb}, {0xfd3e, 0xfd3f}, {0xfe10, 0xfe19}, {0xfe30, 0xfe52},
  {0xfe54, 0xfe61}, {0xfe63, 0xfe63}, {0xfe68, 0xfe68}, {0xfe6a, 0xfe6b}, {0xff01, 0xff03}, {0xff05, 0xff0a}, {0xff0c, 0xff0f}, {0xff1a, 0xff1b},
  {0xff1f, 0xff20}, {0xff3b, 0xff3d}, {0xff3f, 0xff3f}, {0xff5b, 0xff5b}, {0xff5d, 0xff5d}, {0xff5f, 0xff65}, {0x10100, 0x10102}, {0x1039f, 0x1039f},
  {0x103d0, 0x103d0}, {0x1056f, 0x1056f}, {0x10857, 0x10857}, {0x1091f, 0x1091f}, {0x1093f, 0x1093f}, {0x10a50, 0x10a58}, {0x10a7f, 0x10a7f}, {0x10af0, 0x10af6},
  {0x10b39, 0x10b3f}, {0x10b99, 0x10b9c}, {0x10d6e, 0x10d6e}, {0x10ead, 0x10ead}, {0x10f55, 0x10f59}, {0x10f86, 0x10f89}, {0x11047, 0x1104d}, {0x110bb, 0x110bc},
  {0x110be, 0x110c1}, {0x11140, 0x11143}, {0x11174, 0x11175}, {0x111c5, 0x111c8}, {0x111cd, 0x111cd}, {0x111db, 0x111db}, {0x111dd, 0x111df}, {0x11238, 0x1123d},
  {0x112a9, 0x112a9}, {0x113d4, 0x113d5}, {0x113d7, 0x113d8}, {0x1144b, 0x1144f}, {0x1145a, 0x1145b}, {0x1145d, 0x1145d}, {0x114c6, 0x114c6}, {0x115c1, 0x115d7},
  {0x11641, 0x11643}, {0x11660, 0x1166c}, {0x116b9, 0x116b9}, {0x1173c, 0x1173e}, {0x1183b, 0x1183b}, {0x11944, 0x11946}, {0x119e2, 0x119e2}, {0x11a3f, 0x11a46},
  {0x11a9a, 0x11a9c}, {0x11a9e, 0x11aa2}, {0x11b00, 0x11b09}, {0x11be1, 0x11be1}, {0x11c41, 0x11c45}, {0x11c70, 0x11c71}, {0x11ef7, 0x11ef8}, {0x11f43, 0x11f4f},
  {0x11fff, 0x11fff}, {0x12470, 0x12474}, {0x12ff1, 0x12ff2}, {0x16a6e, 0x16a6f}, {0x16af5, 0x16af5}, {0x16b37, 0x16b3b}, {0x16b44, 0x16b44}, {0x16d6d, 0x16d6f},
  {0x16e97, 0x16e9a}, {0x16fe2, 0x16fe2}, {0x1bc9f, 0x1bc9f}, {0x1da87, 0x1da8b}, {0x1e5ff, 0x1e5ff}, {0x1e95e, 0x1e95f},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        '\n', 58,
        '\r', 58,
        '!', 110,
        '"', 144,
        '#', 60,
        '\'', 145,
        '(', 112,
        ')', 114,
        '*', 146,
        ',', 113,
        '.', 148,
        ':', 111,
        '<', 53,
        '@', 150,
        'B', 103,
        '_', 109,
        '`', 33,
        'h', 106,
        'w', 108,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(143);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 154,
        '!', 110,
        '"', 144,
        '#', 149,
        '\'', 145,
        '(', 112,
        '*', 146,
        '-', 147,
        '.', 148,
        ':', 111,
        '<', 53,
        '@', 150,
        '_', 75,
        '`', 37,
        'h', 72,
        'w', 74,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(143);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 154,
        '"', 144,
        '#', 149,
        '\'', 145,
        '(', 112,
        '*', 146,
        '-', 147,
        '.', 148,
        '<', 53,
        '@', 150,
        '_', 75,
        '`', 37,
        'h', 72,
        'w', 74,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(143);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(154);
      if (lookahead == ':') ADVANCE(59);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 144,
        '#', 149,
        '\'', 145,
        '*', 146,
        '-', 147,
        '.', 148,
        '<', 53,
        '@', 150,
        '_', 75,
        '`', 37,
        'h', 72,
        'w', 74,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(143);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(140);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(141);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == ')') ADVANCE(114);
      if (lookahead == ',') ADVANCE(113);
      if (lookahead == '@') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(118);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(138);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '\'') ADVANCE(139);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(132);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '*') ADVANCE(135);
      END_STATE();
    case 14:
      if (lookahead == '*') ADVANCE(136);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == '*') ADVANCE(134);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 18:
      if (lookahead == ',') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == '/') ADVANCE(50);
      END_STATE();
    case 20:
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '/') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == '1') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 23:
      if (lookahead == '1') ADVANCE(18);
      END_STATE();
    case 24:
      if (lookahead == '2') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == '2') ADVANCE(42);
      END_STATE();
    case 26:
      if (lookahead == '>') ADVANCE(137);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 27:
      if (lookahead == 'A') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'C') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(120);
      END_STATE();
    case 30:
      if (lookahead == 'G') ADVANCE(29);
      END_STATE();
    case 31:
      if (lookahead == 'H') ADVANCE(27);
      END_STATE();
    case 32:
      if (lookahead == 'N') ADVANCE(30);
      END_STATE();
    case 33:
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(131);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 35:
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 36:
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(129);
      if (lookahead == '}') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 37:
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 38:
      if (lookahead == '\\') ADVANCE(157);
      if (lookahead == '`') ADVANCE(129);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(159);
      if (lookahead != 0) ADVANCE(158);
      END_STATE();
    case 39:
      if (lookahead == '`') ADVANCE(152);
      END_STATE();
    case 40:
      if (lookahead == '`') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0) ADVANCE(156);
      END_STATE();
    case 41:
      if (lookahead == '`') ADVANCE(39);
      if (lookahead == '{') ADVANCE(23);
      END_STATE();
    case 42:
      if (lookahead == '}') ADVANCE(54);
      END_STATE();
    case 43:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':') ADVANCE(51);
      END_STATE();
    case 44:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(44);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 45:
      if (lookahead == '#' ||
          lookahead == ':') ADVANCE(119);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 49:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 50:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(127);
      END_STATE();
    case 51:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ':') ADVANCE(62);
      END_STATE();
    case 52:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(63);
      END_STATE();
    case 53:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(26);
      END_STATE();
    case 54:
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(159);
      END_STATE();
    case 55:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        '\n', 58,
        '\r', 58,
        '"', 144,
        '#', 60,
        '\'', 145,
        '(', 112,
        ')', 114,
        '*', 146,
        ',', 113,
        '.', 148,
        ':', 59,
        '<', 53,
        '@', 150,
        'B', 103,
        '_', 109,
        '`', 33,
        'h', 106,
        'w', 108,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(143);
      END_STATE();
    case 56:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        '"', 144,
        '#', 61,
        '\'', 145,
        '*', 146,
        '-', 147,
        '.', 148,
        '<', 53,
        '@', 150,
        'B', 86,
        '_', 92,
        '`', 34,
        'h', 89,
        'w', 91,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(56);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (set_contains(sym_punctuation_character_set_1, 198, lookahead)) ADVANCE(143);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_documentation_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_comment_delimeter);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment_delimeter);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_comment_property);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ':') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_comment_string);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == ' ') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '.') ADVANCE(50);
      if (lookahead == '/') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '.') ADVANCE(46);
      if (lookahead == '/') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 's') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == ':') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'p') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 't') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 't') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'w') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'w') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '/') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '.') ADVANCE(124);
      if (lookahead == '/') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '-' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '.') ADVANCE(123);
      if (lookahead == '/') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '-' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 's') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(') ADVANCE(126);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == ':') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(') ADVANCE(126);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'A') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'E') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'G') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'I') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'K') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'N') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'R') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'p') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 't') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 't') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'w') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == 'w') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '-') ADVANCE(122);
      if (lookahead == '/') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '.') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == '.') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == 's') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(') ADVANCE(126);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == ':') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(') ADVANCE(126);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'A') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'E') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'G') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'I') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'K') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'N') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'R') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'p') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 't') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 't') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'w') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (lookahead == 'w') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_task_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_COLON2);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym__scope_name_token1);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '@' || 'Z' < lookahead)) ADVANCE(118);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym__scope_name_token1);
      if (lookahead == '/') ADVANCE(117);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '@' || 'Z' < lookahead)) ADVANCE(118);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym__scope_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '-' &&
          (lookahead < '@' || 'Z' < lookahead)) ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym__scope_name_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != '@') ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_footer_token1);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_BREAKINGCHANGE);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_footer_type_token1);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_footer_type_token1);
      if (lookahead == '/') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(122);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '/' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_footer_type_token1);
      if (lookahead == '!' ||
          lookahead == '#' ||
          lookahead == '(' ||
          lookahead == ':') ADVANCE(127);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!') ADVANCE(123);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_footer_type_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_footer_type_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(121);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(126);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_footer_type_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ':') ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_issue_reference);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_code);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_code);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '`') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_code);
      if (lookahead == '`') ADVANCE(152);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_italic);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_italic);
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(11);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_italic);
      if (lookahead == '*') ADVANCE(132);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_bold);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_bold);
      if (lookahead == '*') ADVANCE(135);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_autolink);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_single_quote);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_single_quote);
      if (lookahead == '\'') ADVANCE(138);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_double_quote);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_double_quote);
      if (lookahead == '"') ADVANCE(140);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(5);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '"') ADVANCE(140);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(5);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '\'') ADVANCE(138);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(9);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '*') ADVANCE(133);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_punctuation);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_punctuation);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_punctuation);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_mention);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_code_block_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(153);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_code_block_token2);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_code_block_content_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(156);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_code_block_content_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(156);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_code_block_content_token2);
      if (lookahead == '\\') ADVANCE(157);
      if (lookahead == '`') ADVANCE(130);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(159);
      if (lookahead != 0) ADVANCE(158);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_code_block_content_token2);
      if (lookahead == '\\') ADVANCE(157);
      if (lookahead == '`') ADVANCE(129);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(159);
      if (lookahead != 0) ADVANCE(158);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(aux_sym_code_block_content_token2);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(159);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 56},
  [2] = {.lex_state = 56},
  [3] = {.lex_state = 56},
  [4] = {.lex_state = 56},
  [5] = {.lex_state = 1, .external_lex_state = 1},
  [6] = {.lex_state = 4, .external_lex_state = 1},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4, .external_lex_state = 1},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4, .external_lex_state = 1},
  [13] = {.lex_state = 40},
  [14] = {.lex_state = 40},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 40},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 3, .external_lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0, .external_lex_state = 1},
  [35] = {.lex_state = 0, .external_lex_state = 1},
  [36] = {.lex_state = 0, .external_lex_state = 1},
  [37] = {.lex_state = 0, .external_lex_state = 1},
  [38] = {.lex_state = 0, .external_lex_state = 1},
  [39] = {.lex_state = 0, .external_lex_state = 1},
  [40] = {.lex_state = 43},
  [41] = {.lex_state = 45},
  [42] = {.lex_state = 0, .external_lex_state = 1},
  [43] = {.lex_state = 45},
  [44] = {.lex_state = 44},
  [45] = {.lex_state = 0, .external_lex_state = 1},
  [46] = {.lex_state = 0, .external_lex_state = 1},
  [47] = {.lex_state = 0, .external_lex_state = 1},
  [48] = {.lex_state = 0, .external_lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_documentation_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_comment_delimeter] = ACTIONS(1),
    [aux_sym_task_token1] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_COLON2] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [aux_sym_footer_token1] = ACTIONS(1),
    [anon_sym_BREAKINGCHANGE] = ACTIONS(1),
    [aux_sym_footer_type_token1] = ACTIONS(1),
    [sym_url] = ACTIONS(1),
    [sym_code] = ACTIONS(1),
    [sym_italic] = ACTIONS(1),
    [sym_bold] = ACTIONS(1),
    [sym_autolink] = ACTIONS(1),
    [sym_single_quote] = ACTIONS(1),
    [sym_double_quote] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_mention] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [aux_sym_code_block_token2] = ACTIONS(1),
    [aux_sym_code_block_content_token2] = ACTIONS(1),
    [sym_newlinw_or_eof] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_documentation] = STATE(33),
    [sym__documentation_component] = STATE(37),
    [sym_comment] = STATE(37),
    [sym__property_comment] = STATE(38),
    [sym__content_comment] = STATE(39),
    [sym_task] = STATE(37),
    [sym_footer] = STATE(37),
    [sym_footer_type] = STATE(43),
    [sym_string] = STATE(45),
    [sym__string_component] = STATE(6),
    [sym_word] = STATE(6),
    [sym_code_block] = STATE(37),
    [aux_sym_documentation_repeat1] = STATE(3),
    [aux_sym_string_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_documentation_token1] = ACTIONS(5),
    [sym_comment_delimeter] = ACTIONS(7),
    [aux_sym_task_token1] = ACTIONS(9),
    [anon_sym_BREAKINGCHANGE] = ACTIONS(11),
    [aux_sym_footer_type_token1] = ACTIONS(13),
    [sym_url] = ACTIONS(15),
    [sym_issue_reference] = ACTIONS(17),
    [sym_code] = ACTIONS(15),
    [sym_italic] = ACTIONS(15),
    [sym_bold] = ACTIONS(17),
    [sym_autolink] = ACTIONS(17),
    [sym_single_quote] = ACTIONS(17),
    [sym_double_quote] = ACTIONS(17),
    [sym_number] = ACTIONS(15),
    [sym_punctuation] = ACTIONS(15),
    [sym_mention] = ACTIONS(17),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__documentation_component] = STATE(37),
    [sym_comment] = STATE(37),
    [sym__property_comment] = STATE(38),
    [sym__content_comment] = STATE(39),
    [sym_task] = STATE(37),
    [sym_footer] = STATE(37),
    [sym_footer_type] = STATE(43),
    [sym_string] = STATE(45),
    [sym__string_component] = STATE(6),
    [sym_word] = STATE(6),
    [sym_code_block] = STATE(37),
    [aux_sym_documentation_repeat1] = STATE(2),
    [aux_sym_string_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(21),
    [aux_sym_documentation_token1] = ACTIONS(23),
    [sym_comment_delimeter] = ACTIONS(26),
    [aux_sym_task_token1] = ACTIONS(29),
    [anon_sym_BREAKINGCHANGE] = ACTIONS(32),
    [aux_sym_footer_type_token1] = ACTIONS(35),
    [sym_url] = ACTIONS(38),
    [sym_issue_reference] = ACTIONS(41),
    [sym_code] = ACTIONS(38),
    [sym_italic] = ACTIONS(38),
    [sym_bold] = ACTIONS(41),
    [sym_autolink] = ACTIONS(41),
    [sym_single_quote] = ACTIONS(41),
    [sym_double_quote] = ACTIONS(41),
    [sym_number] = ACTIONS(38),
    [sym_punctuation] = ACTIONS(38),
    [sym_mention] = ACTIONS(41),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(44),
  },
  [STATE(3)] = {
    [sym__documentation_component] = STATE(37),
    [sym_comment] = STATE(37),
    [sym__property_comment] = STATE(38),
    [sym__content_comment] = STATE(39),
    [sym_task] = STATE(37),
    [sym_footer] = STATE(37),
    [sym_footer_type] = STATE(43),
    [sym_string] = STATE(45),
    [sym__string_component] = STATE(6),
    [sym_word] = STATE(6),
    [sym_code_block] = STATE(37),
    [aux_sym_documentation_repeat1] = STATE(2),
    [aux_sym_string_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(47),
    [aux_sym_documentation_token1] = ACTIONS(49),
    [sym_comment_delimeter] = ACTIONS(7),
    [aux_sym_task_token1] = ACTIONS(9),
    [anon_sym_BREAKINGCHANGE] = ACTIONS(11),
    [aux_sym_footer_type_token1] = ACTIONS(13),
    [sym_url] = ACTIONS(15),
    [sym_issue_reference] = ACTIONS(17),
    [sym_code] = ACTIONS(15),
    [sym_italic] = ACTIONS(15),
    [sym_bold] = ACTIONS(17),
    [sym_autolink] = ACTIONS(17),
    [sym_single_quote] = ACTIONS(17),
    [sym_double_quote] = ACTIONS(17),
    [sym_number] = ACTIONS(15),
    [sym_punctuation] = ACTIONS(15),
    [sym_mention] = ACTIONS(17),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(51), 8,
      sym_comment_delimeter,
      aux_sym_task_token1,
      aux_sym_footer_type_token1,
      sym_url,
      sym_code,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(21), 10,
      ts_builtin_sym_end,
      aux_sym_documentation_token1,
      anon_sym_BREAKINGCHANGE,
      sym_issue_reference,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [23] = 6,
    ACTIONS(55), 1,
      anon_sym_BANG,
    ACTIONS(57), 1,
      anon_sym_COLON2,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_task_scope,
    ACTIONS(53), 4,
      aux_sym_task_token1,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(61), 9,
      sym_newlinw_or_eof,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [53] = 5,
    ACTIONS(63), 1,
      aux_sym_task_token1,
    ACTIONS(69), 1,
      sym_newlinw_or_eof,
    ACTIONS(67), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(9), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(65), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [80] = 5,
    ACTIONS(63), 1,
      aux_sym_task_token1,
    STATE(34), 1,
      sym_string,
    ACTIONS(15), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(6), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(17), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [107] = 5,
    ACTIONS(63), 1,
      aux_sym_task_token1,
    STATE(46), 1,
      sym_string,
    ACTIONS(15), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(6), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(17), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [134] = 5,
    ACTIONS(71), 1,
      aux_sym_task_token1,
    ACTIONS(80), 1,
      sym_newlinw_or_eof,
    ACTIONS(77), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(9), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(74), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [161] = 5,
    ACTIONS(63), 1,
      aux_sym_task_token1,
    STATE(36), 1,
      sym_string,
    ACTIONS(15), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(6), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(17), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [188] = 5,
    ACTIONS(63), 1,
      aux_sym_task_token1,
    STATE(47), 1,
      sym_string,
    ACTIONS(15), 3,
      sym_italic,
      sym_number,
      sym_punctuation,
    STATE(6), 3,
      sym__string_component,
      sym_word,
      aux_sym_string_repeat1,
    ACTIONS(17), 8,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [215] = 2,
    ACTIONS(53), 4,
      aux_sym_task_token1,
      sym_italic,
      sym_number,
      sym_punctuation,
    ACTIONS(61), 9,
      sym_newlinw_or_eof,
      sym_url,
      sym_issue_reference,
      sym_code,
      sym_bold,
      sym_autolink,
      sym_single_quote,
      sym_double_quote,
      sym_mention,
  [233] = 4,
    ACTIONS(82), 1,
      aux_sym_code_block_content_token1,
    ACTIONS(84), 1,
      aux_sym_code_block_content_token2,
    STATE(16), 1,
      aux_sym_code_block_content_repeat1,
    STATE(32), 1,
      sym_code_block_content,
  [246] = 4,
    ACTIONS(82), 1,
      aux_sym_code_block_content_token1,
    ACTIONS(84), 1,
      aux_sym_code_block_content_token2,
    STATE(16), 1,
      aux_sym_code_block_content_repeat1,
    STATE(28), 1,
      sym_code_block_content,
  [259] = 3,
    ACTIONS(86), 1,
      aux_sym__scope_name_token1,
    STATE(19), 1,
      sym__scope_name,
    ACTIONS(88), 2,
      sym_issue_reference,
      sym_mention,
  [270] = 4,
    ACTIONS(90), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(92), 1,
      aux_sym_code_block_content_token1,
    ACTIONS(94), 1,
      aux_sym_code_block_content_token2,
    STATE(18), 1,
      aux_sym_code_block_content_repeat1,
  [283] = 3,
    ACTIONS(96), 1,
      aux_sym__scope_name_token1,
    STATE(26), 1,
      sym__scope_name,
    ACTIONS(98), 2,
      sym_issue_reference,
      sym_mention,
  [294] = 4,
    ACTIONS(100), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(102), 1,
      aux_sym_code_block_content_token1,
    ACTIONS(105), 1,
      aux_sym_code_block_content_token2,
    STATE(18), 1,
      aux_sym_code_block_content_repeat1,
  [307] = 3,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      aux_sym_task_scope_repeat1,
  [317] = 3,
    ACTIONS(108), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      aux_sym_task_scope_repeat1,
  [327] = 3,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      aux_sym_task_scope_repeat1,
  [337] = 2,
    ACTIONS(119), 1,
      anon_sym_COLON,
    ACTIONS(121), 1,
      sym_newlinw_or_eof,
  [344] = 1,
    ACTIONS(123), 2,
      anon_sym_BANG,
      anon_sym_COLON2,
  [349] = 2,
    ACTIONS(125), 1,
      aux_sym_code_block_token1,
    ACTIONS(127), 1,
      aux_sym_code_block_token2,
  [356] = 2,
    ACTIONS(129), 1,
      anon_sym_BANG,
    ACTIONS(131), 1,
      anon_sym_COLON2,
  [363] = 1,
    ACTIONS(117), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [368] = 1,
    ACTIONS(133), 2,
      anon_sym_BANG,
      anon_sym_COLON2,
  [373] = 1,
    ACTIONS(135), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [377] = 1,
    ACTIONS(137), 1,
      aux_sym_code_block_token2,
  [381] = 1,
    ACTIONS(139), 1,
      anon_sym_COLON2,
  [385] = 1,
    ACTIONS(131), 1,
      anon_sym_COLON2,
  [389] = 1,
    ACTIONS(141), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [393] = 1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
  [397] = 1,
    ACTIONS(145), 1,
      sym_newlinw_or_eof,
  [401] = 1,
    ACTIONS(147), 1,
      sym_newlinw_or_eof,
  [405] = 1,
    ACTIONS(149), 1,
      sym_newlinw_or_eof,
  [409] = 1,
    ACTIONS(151), 1,
      sym_newlinw_or_eof,
  [413] = 1,
    ACTIONS(153), 1,
      sym_newlinw_or_eof,
  [417] = 1,
    ACTIONS(155), 1,
      sym_newlinw_or_eof,
  [421] = 1,
    ACTIONS(157), 1,
      sym_comment_property,
  [425] = 1,
    ACTIONS(159), 1,
      aux_sym_footer_token1,
  [429] = 1,
    ACTIONS(161), 1,
      sym_newlinw_or_eof,
  [433] = 1,
    ACTIONS(163), 1,
      aux_sym_footer_token1,
  [437] = 1,
    ACTIONS(165), 1,
      sym_comment_string,
  [441] = 1,
    ACTIONS(167), 1,
      sym_newlinw_or_eof,
  [445] = 1,
    ACTIONS(169), 1,
      sym_newlinw_or_eof,
  [449] = 1,
    ACTIONS(171), 1,
      sym_newlinw_or_eof,
  [453] = 1,
    ACTIONS(173), 1,
      sym_newlinw_or_eof,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 23,
  [SMALL_STATE(6)] = 53,
  [SMALL_STATE(7)] = 80,
  [SMALL_STATE(8)] = 107,
  [SMALL_STATE(9)] = 134,
  [SMALL_STATE(10)] = 161,
  [SMALL_STATE(11)] = 188,
  [SMALL_STATE(12)] = 215,
  [SMALL_STATE(13)] = 233,
  [SMALL_STATE(14)] = 246,
  [SMALL_STATE(15)] = 259,
  [SMALL_STATE(16)] = 270,
  [SMALL_STATE(17)] = 283,
  [SMALL_STATE(18)] = 294,
  [SMALL_STATE(19)] = 307,
  [SMALL_STATE(20)] = 317,
  [SMALL_STATE(21)] = 327,
  [SMALL_STATE(22)] = 337,
  [SMALL_STATE(23)] = 344,
  [SMALL_STATE(24)] = 349,
  [SMALL_STATE(25)] = 356,
  [SMALL_STATE(26)] = 363,
  [SMALL_STATE(27)] = 368,
  [SMALL_STATE(28)] = 373,
  [SMALL_STATE(29)] = 377,
  [SMALL_STATE(30)] = 381,
  [SMALL_STATE(31)] = 385,
  [SMALL_STATE(32)] = 389,
  [SMALL_STATE(33)] = 393,
  [SMALL_STATE(34)] = 397,
  [SMALL_STATE(35)] = 401,
  [SMALL_STATE(36)] = 405,
  [SMALL_STATE(37)] = 409,
  [SMALL_STATE(38)] = 413,
  [SMALL_STATE(39)] = 417,
  [SMALL_STATE(40)] = 421,
  [SMALL_STATE(41)] = 425,
  [SMALL_STATE(42)] = 429,
  [SMALL_STATE(43)] = 433,
  [SMALL_STATE(44)] = 437,
  [SMALL_STATE(45)] = 441,
  [SMALL_STATE(46)] = 445,
  [SMALL_STATE(47)] = 449,
  [SMALL_STATE(48)] = 453,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_documentation, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_documentation, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_documentation_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block_content, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_block_content_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_block_content_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_block_content_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_task_scope_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__content_comment, 2, 0, 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_scope, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_scope, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [143] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footer, 3, 0, 6),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__property_comment, 4, 0, 7),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 4, 0, 8),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_footer_type, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4, 0, 9),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__documentation_component, 1, 0, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 3, 0, 5),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 5, 0, 10),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 5, 0, 11),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_newlinw_or_eof = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_newlinw_or_eof] = sym_newlinw_or_eof,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_newlinw_or_eof] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_doctext_external_scanner_create(void);
void tree_sitter_doctext_external_scanner_destroy(void *);
bool tree_sitter_doctext_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_doctext_external_scanner_serialize(void *, char *);
void tree_sitter_doctext_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_doctext(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_doctext_external_scanner_create,
      tree_sitter_doctext_external_scanner_destroy,
      tree_sitter_doctext_external_scanner_scan,
      tree_sitter_doctext_external_scanner_serialize,
      tree_sitter_doctext_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "doctext",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
